libavcodec_x86_vvc_optional_sources = {
  'vvc_decoder' : files('vvcdsp_init.c') # MANUAL
}

libavcodec_x86_vvc_x86asm_optional_sources = {
  'vvc_decoder' : files('vvc_mc.asm') # MANUAL
}

libavcodec_x86_vvc_armv5te_optional_sources = {
}

libavcodec_x86_vvc_armv6_optional_sources = {
}

libavcodec_x86_vvc_armv8_optional_sources = {
}

libavcodec_x86_vvc_neon_optional_sources = {
}

libavcodec_x86_vvc_vfp_optional_sources = {
}

libavcodec_x86_vvc_mmx_optional_sources = {
}

libavcodec_x86_vvc_shlib_optional_sources = {
}

libavcodec_x86_vvc_slib_optional_sources = {
}

libavcodec_x86_vvc_optional_tests = {
}

