libavcodec_vvc_optional_sources = {
  'vvc_decoder' : files('vvcdec.c','vvcdsp.c','vvc_cabac.c','vvc_ctu.c','vvc_data.c','vvc_filter.c','vvc_inter.c','vvc_intra.c','vvc_intra_utils.c','vvc_itx_1d.c','vvc_mvs.c','vvc_ps.c','vvc_refs.c','vvc_thread.c'),
}

libavcodec_vvc_x86asm_optional_sources = {
}

libavcodec_vvc_armv5te_optional_sources = {
}

libavcodec_vvc_armv6_optional_sources = {
}

libavcodec_vvc_armv8_optional_sources = {
}

libavcodec_vvc_neon_optional_sources = {
}

libavcodec_vvc_vfp_optional_sources = {
}

libavcodec_vvc_mmx_optional_sources = {
}

libavcodec_vvc_shlib_optional_sources = {
}

libavcodec_vvc_slib_optional_sources = {
}

libavcodec_vvc_optional_tests = {
}

