libavcodec_vvc_optional_sources = {
  'vvc_decoder' : files('dec.c','dsp.c','cabac.c','ctu.c','data.c','filter.c','inter.c','intra.c','intra_utils.c','itx_1d.c','mvs.c','ps.c','refs.c','thread.c'),
}

libavcodec_vvc_x86asm_optional_sources = {
}

libavcodec_vvc_armv5te_optional_sources = {
}

libavcodec_vvc_armv6_optional_sources = {
}

libavcodec_vvc_armv8_optional_sources = {
}

libavcodec_vvc_neon_optional_sources = {
}

libavcodec_vvc_vfp_optional_sources = {
}

libavcodec_vvc_mmx_optional_sources = {
}

libavcodec_vvc_shlib_optional_sources = {
}

libavcodec_vvc_slib_optional_sources = {
}

libavcodec_vvc_optional_tests = {
}

