libavcodec_hevc_optional_sources = {
  'hevcparse' : files('data.c','parse.c','ps.c'),
  'hevc_decoder' : files('cabac.c','data.c','dsp.c','filter.c','hevcdec.c','mvs.c','pred.c','refs.c'),
  'hevc_parser' : files('parser.c'),
  'hevc_sei' : files('sei.c'),
}

libavcodec_hevc_x86asm_optional_sources = {
}

libavcodec_hevc_armv5te_optional_sources = {
}

libavcodec_hevc_armv6_optional_sources = {
}

libavcodec_hevc_armv8_optional_sources = {
}

libavcodec_hevc_neon_optional_sources = {
}

libavcodec_hevc_vfp_optional_sources = {
}

libavcodec_hevc_mmx_optional_sources = {
}

libavcodec_hevc_shlib_optional_sources = {
}

libavcodec_hevc_slib_optional_sources = {
}

libavcodec_hevc_optional_tests = {
}

