libavcodec_aac_optional_sources = {
  'aac_decoder' : files('aacdec.c','aacdec_tab.c','aacdec_float.c','aacdec_usac.c','aacdec_ac.c','aacdec_lpd.c'),
  'aac_fixed_decoder' : files('aacdec.c','aacdec_tab.c','aacdec_fixed.c'),
}

libavcodec_aac_x86asm_optional_sources = {
}

libavcodec_aac_armv5te_optional_sources = {
}

libavcodec_aac_armv6_optional_sources = {
}

libavcodec_aac_armv8_optional_sources = {
}

libavcodec_aac_neon_optional_sources = {
}

libavcodec_aac_vfp_optional_sources = {
}

libavcodec_aac_mmx_optional_sources = {
}

libavcodec_aac_shlib_optional_sources = {
}

libavcodec_aac_slib_optional_sources = {
}

libavcodec_aac_optional_tests = {
}

