libavcodec_aarch64_vvc_optional_sources = {
  'vvc_decoder' : files('dsp_init.c'),
}

libavcodec_aarch64_vvc_x86asm_optional_sources = {
}

libavcodec_aarch64_vvc_armv5te_optional_sources = {
}

libavcodec_aarch64_vvc_armv6_optional_sources = {
}

libavcodec_aarch64_vvc_armv8_optional_sources = {
}

libavcodec_aarch64_vvc_neon_optional_sources = {
  'vvc_decoder' : files('alf.S','inter.S','sad.S'), # MANUAL
}

libavcodec_aarch64_vvc_vfp_optional_sources = {
}

libavcodec_aarch64_vvc_mmx_optional_sources = {
}

libavcodec_aarch64_vvc_shlib_optional_sources = {
}

libavcodec_aarch64_vvc_slib_optional_sources = {
}

libavcodec_aarch64_vvc_optional_tests = {
}

