libavcodec_opus_optional_sources = {
  'opus_decoder' : files('dec.c','dec_celt.c','celt.c','pvq.c','silk.c','tab.c','dsp.c','parse.c','rc.c'),
  'opus_encoder' : files('enc.c','enc_psy.c','celt.c','pvq.c','rc.c','tab.c'),
  'opus_parser' : files('parser.c','parse.c'),
}

libavcodec_opus_x86asm_optional_sources = {
}

libavcodec_opus_armv5te_optional_sources = {
}

libavcodec_opus_armv6_optional_sources = {
}

libavcodec_opus_armv8_optional_sources = {
}

libavcodec_opus_neon_optional_sources = {
}

libavcodec_opus_vfp_optional_sources = {
}

libavcodec_opus_mmx_optional_sources = {
}

libavcodec_opus_shlib_optional_sources = {
}

libavcodec_opus_slib_optional_sources = {
}

libavcodec_opus_optional_tests = {
}

